version: '3.8'

services:
  frontend:
    build:
      context: ./
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${VITE_API_URL}

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
