version: '3.8'

services:
  frontend:
    build:
      context: ./
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_API_URL: ${VITE_API_URL}   # runtime me Jenkinsfile se pass hoga

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env             # Jenkinsfile se dynamically create hoga
