version: '3.8'

services:
  frontend:
    build:
      context: ./   # basic folder ke andar hi frontend code hai
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://backend:5000

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
